<a href="https://colab.research.google.com/github/JSJeong-me/KOSA-Pytorch/blob/main/1_linear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
x = torch.randn(2,3)

In [4]:
y = torch.rand(2,3)

In [4]:
a = x.to('cuda')

In [ ]:
#python

In [ ]:
# Y = Wx + b
# input: 10 Ouput: 5 Linear Transform

In [ ]:
import torch
from torch.autograd import Variable
from torch.nn import Linear

data = Variable(torch.randn(1, 10))
Layer =Linear(in_features=10, out_features=5, bias=True)

In [ ]:
Layer(data)

tensor([[-0.3379, -0.2850,  0.0090, -1.1616,  0.5723]],
       grad_fn=<AddmmBackward>)

In [ ]:
Layer.weight

In [ ]:
Layer.bias

In [ ]:
# Activation Function -> ReLu

In [ ]:
from torch.nn import ReLU
import torch

In [ ]:
data = torch.Tensor([[1, 2, -1, -2]])

In [ ]:
relu = ReLU()
relu(data)

tensor([[1., 2., 0., 0.]])

In [ ]:
# Feedforward & Back Propagation
# https://blog.naver.com/slykid/222007253786

In [ ]:
import torch
from torch import nn
from torch.autograd import Variable

In [ ]:
class Network_ex(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(Network_ex).__init__()
        self.layer1 = nn.Linear(input_size, hidden_size)
        self.layer2 = nn.Linear(hidden_size, output_size)
        
    def forward(self, input):
        out = self.Layer1(input)
        out = nn.ReLU(out)
        out = self.layer2(out)
        
        return out

In [ ]:
loss = nn.MSELoss()
data = Variable(torch.randn(3, 5), requires_grad=True)

In [ ]:
data

tensor([[-1.3343,  0.2266,  1.4069, -0.0098,  1.2536],
        [ 0.7315,  1.0377,  1.2904,  0.7527, -0.4447],
        [ 0.6441,  0.3752, -0.2164,  1.0216,  0.2104]], requires_grad=True)

In [ ]:
target = Variable(torch.randn(3, 5))

In [ ]:
target

tensor([[ 0.1866,  1.1588, -1.7590,  0.7707,  1.0213],
        [-1.7094,  0.3668, -2.0018,  1.6499,  2.1219],
        [ 0.1025,  0.7542,  0.6885, -0.3097, -1.1318]])

In [ ]:
output = loss(data, target)
output.backward()